WITH HOME_SCORES AS (
    SELECT
        GAME_ID,
        TEAM_ID,
        TEAM_OWNER AS HOME_TEAM_OWNER,
        TEAM_PROJECTED_SCORE AS HOME_TEAM_PROJECTED_SCORE,
        TEAM_SCORE AS HOME_TEAM_CURRENT_SCORE
    FROM "DEVELOPMENT"."DONNY"."FANTASY_SCORES" AS FS
    WHERE FS.HOME_AWAY = 'home'
),
AWAY_SCORES AS (
    SELECT
        GAME_ID,
        TEAM_OWNER AS AWAY_TEAM_OWNER,
        TEAM_PROJECTED_SCORE AS AWAY_TEAM_PROJECTED_SCORE,
        TEAM_SCORE AS AWAY_TEAM_CURRENT_SCORE
    FROM "DEVELOPMENT"."DONNY"."FANTASY_SCORES" AS FS
    WHERE FS.HOME_AWAY = 'away'
)

SELECT
    HS.GAME_ID,
    HS.HOME_TEAM_OWNER AS HT_OWNER,
    HS.HOME_TEAM_CURRENT_SCORE AS HT_TRUE,
    HS.HOME_TEAM_PROJECTED_SCORE AS HT_PROJ,
    A.AWAY_TEAM_CURRENT_SCORE AS AT_TRUE,
    A.AWAY_TEAM_PROJECTED_SCORE AS AT_PROJ,
    A.AWAY_TEAM_OWNER AS AT_OWNER,
    CONCAT('https://fantasy.espn.com/football/fantasycast?leagueId=',LEAGUE_ID,'&matchupPeriodId=',FTT.WEEK_NUMBER,'&seasonId=',FTT.YEAR,'&teamId=',FTT.TEAM_ID) AS FANTASYCAST

FROM HOME_SCORES HS
LEFT JOIN AWAY_SCORES AS A ON HS.GAME_ID = A.GAME_ID
LEFT JOIN "DEVELOPMENT"."DONNY"."FANTASY_TIME" FTT ON HS.TEAM_ID = FTT.TEAM_ID