WITH H2H_PROJECTED_WINNERS AS (
    SELECT
        GAME_ID,
        GET(ARRAY_AGG(TEAM_ID) WITHIN GROUP (ORDER BY TEAM_PROJECTED_SCORE DESC), 0) AS PROJECTED_WINNER
    FROM "DEVELOPMENT"."DONNY"."FANTASY_SCORES" AS FS
    GROUP BY 1
),
HOME_TEAM AS (
    SELECT
        GAME_ID,
        TEAM_ID,
        TEAM_PROJECTED_SCORE
    FROM "DEVELOPMENT"."DONNY"."FANTASY_SCORES"
    WHERE HOME_AWAY = 'home'
),
AWAY_TEAM AS (
    SELECT
        GAME_ID,
        TEAM_ID,
        TEAM_PROJECTED_SCORE
    FROM "DEVELOPMENT"."DONNY"."FANTASY_SCORES"
    WHERE HOME_AWAY = 'away'
),
OPPOSING_TEAM_SCORE AS (
    SELECT
        HT.TEAM_ID,
        AW.TEAM_PROJECTED_SCORE
    FROM HOME_TEAM HT
    LEFT JOIN AWAY_TEAM AW ON HT.GAME_ID = AW.GAME_ID
    UNION ALL
    SELECT
        AW.TEAM_ID,
        HT.TEAM_PROJECTED_SCORE
    FROM AWAY_TEAM AW 
    LEFT JOIN HOME_TEAM HT ON HT.GAME_ID = AW.GAME_ID
),
POINTS_FOR_RANKINGS AS (
    SELECT
        FS.TEAM_ID,
        FS.TEAM_PROJECTED_SCORE,
        OT.TEAM_PROJECTED_SCORE AS OPPONENT_PROJECTED_SCORE,
        ROW_NUMBER() OVER(ORDER BY FS.TEAM_PROJECTED_SCORE DESC) AS RANKING
    FROM "DEVELOPMENT"."DONNY"."FANTASY_SCORES" FS
    LEFT JOIN OPPOSING_TEAM_SCORE OT ON FS.TEAM_ID = OT.TEAM_ID
),
AVG_WEEKLY_RANKING AS (
    SELECT 
        FTT.TEAM_ID,
        (PFR.RANKING + (FTT.WEEK_NUMBER - 1) *  FT.AVG_WEEKLY_RANKING)/ FTT.WEEK_NUMBER
            AS PROJECTED_AVG_WEEKLY_RANKING
    FROM "DEVELOPMENT"."DONNY"."FANTASY_TIME" AS FTT
    LEFT JOIN "DEVELOPMENT"."DONNY"."FANTASY_TEAMS" AS FT ON FTT.TEAM_ID = FT.ID
    LEFT JOIN POINTS_FOR_RANKINGS PFR ON FTT.TEAM_ID = PFR.TEAM_ID
),
CLEANED_TEAMS AS (
    SELECT 
        FT.ID AS TEAM_ID,
        FT.OWNER,
        FT.POINTS_FOR + PFR.TEAM_PROJECTED_SCORE AS PROJECTED_POINTS_FOR,
        FT.POINTS_AGAINST + PFR.OPPONENT_PROJECTED_SCORE AS PROJECTED_POINTS_AGAINST,
        FT.HEAD_TO_HEAD_WINS + IFF(H2H_PW.GAME_ID IS NOT NULL,1,0) AS PROJECTED_H2H_WINS,
        FT.HEAD_TO_HEAD_LOSSES + IFF(H2H_PW.GAME_ID IS NOT NULL,0,1) AS PROJECTED_H2H_LOSSES,
        FT.POINTS_FOR_WINS + IFF(PFR.RANKING < 7,1,0) AS PROJECTED_POINTS_FOR_WINS,
        FT.POINTS_FOR_LOSSES + IFF(PFR.RANKING < 7,0,1) AS PROJECTED_POINTS_FOR_LOSSES,
        FT.WEEKS_TOP_SCORER + IFF(PFR.RANKING = 1, 1, 0) AS PROJECTED_WEEKS_TOP_SCORER,
        FT.WEEKS_BOTTOM_SCORER + IFF(PFR.RANKING = 12, 1, 0) AS PROJECTED_WEEKS_BOTTOM_SCORER,
        AWR.PROJECTED_AVG_WEEKLY_RANKING
    FROM "DEVELOPMENT"."DONNY"."FANTASY_TEAMS" AS FT
    LEFT JOIN H2H_PROJECTED_WINNERS AS H2H_PW ON FT.ID = H2H_PW.PROJECTED_WINNER
    LEFT JOIN POINTS_FOR_RANKINGS AS PFR ON FT.ID = PFR.TEAM_ID
    LEFT JOIN AVG_WEEKLY_RANKING AS AWR ON FT.ID = AWR.TEAM_ID
)

SELECT 
    CT.PROJECTED_H2H_WINS + CT.PROJECTED_POINTS_FOR_WINS AS TOTAL_WINS,
    CT.PROJECTED_H2H_LOSSES + CT.PROJECTED_POINTS_FOR_LOSSES AS TOTAL_LOSSES,
    CT.*
FROM CLEANED_TEAMS AS CT
ORDER BY 1 DESC, 5 DESC, 4 DESC